server:
  port: 443
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.jks
    key-store-password: 123456
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096
spring:
  application:
    name: incallup
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
  show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver: com.mysql.jdbc.Driver
    username: sql6683807
#    username: root
    password: pzieJzTC9W
#    password: hello
    url: jdbc:mysql://sql6.freesqldatabase.com:3306/?user=sql6683807
#    url: jdbc:mysql://localhost:3306/incallup
