springdoc:
  version: v1
  api-docs:
    path: /incallup
  swagger-ui:
    disable-swagger-default-url: true
    path: /incallup/swagger/ui/show
logging:
  level:
    sql: debug
    web: debug
#    root: error
#    org:
#      springframework:
#        data:
#          jpa: trace
#        jdbc: debug
#      hibernate:
#        SQL: debug
#        ORM:
#          jdbc:
#            bind: trace
server:
  port: 443
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:incallup.com.jks
#    key-store: classpath:keystore.jks
    key-store-password: 123456

  compression:
    enabled: true
#    mime-types: text/xml , text/css , text/html , application/json
    min-response-size: 4096
spring:
#  devtools:
#    restart:
#      additional-paths: src/main/resources/static , src/main/resources/templates
  application:
    name: incallup
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: incallup_incallup
    password: B=3hX4SkiNE,
    url: jdbc:mysql://62.171.171.251:3306/incallup_db

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: hello
#    url: jdbc:mysql://localhost:3306/incallup



#    url: jdbc:mysql://sql6.freesqldatabase.com:3306/sql6683807
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: incallup_incallup
#    password: 4booiVOPDhVws59d2
#    url: jdbc:mysql://aws.connect.psdb.cloud/incallup?sslMode=VERIFY_IDENTITY

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: 0tvxbdvfz91d9ssp1wb0
#    password: pscale_pw_qdrhvew3NsTZxKvnGxr73YgDG8mgsXLfvNcojPjDaBB
#    url: jdbc:mysql://aws.connect.psdb.cloud/incallup?sslMode=VERIFY_IDENTITY

#    username: ${DBUSERNAME}
#    password: ${DBPASS}
#    url: ${DBURL}


whm:
  ftp:
    port: 22
    server: 62.171.171.251
    username: root
    password: 4booiVOPDhVws59d2
    path: /inctest/
    sessionTimeout: 15000
    channelTimeout: 15000
#    port: 21
#    username: dev
#    password: 2NNx]l-9tgBn
