springdoc:
  api-docs:
    path: /incallup
  swagger-ui:
    version: v1
    disable-swagger-default-url: true
    path: /incallup/swagger/ui
logging:
  level:
    sql: trace
    root: trace
    web: trace
#    org:
#      springframework:
#        data:
#          jpa: trace
#        jdbc: debug
#      hibernate:
#        SQL: debug
#        ORM:
#          jdbc:
#            bind: trace
server:
  port: 443
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.jks
    key-store-password: 123456

  compression:
    enabled: true
    mime-types: text/xml , text/css , text/html , application/json
    min-response-size: 4096
spring:
#  devtools:
#    restart:
#      additional-paths: src/main/resources/static , src/main/resources/templates
  application:
    name: incallup
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sql6683807
    password: pzieJzTC9W
    url: jdbc:mysql://sql6.freesqldatabase.com:3306/sql6683807
#    username: root
#    password: hello
#    url: jdbc:mysql://localhost:3306/incallup
