
server:
  port: 8081

  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096

spring:
  application:
    name: incallup
  jpa:
    hibernate:
      ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
  show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver: com.mysql.jdbc.Driver
    username: root
    password: hello
    url: jdbc:mysql://localhost:3306/incallup
