
server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver: com.mysql.jdbc.Driver
    username: root
    password: hello
    url: jdbc:mysql://localhost:3306/incallup